setwd("C:/Users/Sara/Desktop/Tesis/Cursos bioinformatica/Curso_R/ExData_Plotting1")
data_full <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?", nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
data1 <- subset(data_full, Date %in% c("1/2/2007","2/2/2007"))
data1$Date <- as.Date(data1$Date, format="%d/%m/%Y")
datatime <- paste(as.Date(data1$Date, data1$Timeti))
data1$Datetime <- as.POSIXct(datetime)
with(data1, { plot(Global_active_power~Datetime, type="l", ylab="Global Active Power (kilowatts)", xlab="")})
title(main=" Global Active Power vs time")
dev.copy(png,"plot2.png", width=480, height=480)
dev.off()