setwd("C:/Users/Sara/Desktop/Tesis/Cursos bioinformatica/Curso_R/ExData_Plotting1")
data_full <- read.csv("household_power_consumption.txt", header=T, sep=';', na.strings="?", nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
data1 <- subset(data_full, Date %in% c("1/2/2007","2/2/2007"))
data1$Date <- as.Date(data1$Date, format="%d/%m/%Y")
datatime <- paste(as.Date(data1$Date, data1$Timeti))
data1$Datetime <- as.POSIXct(datetime)
par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(0,0,2,0))
with(data1, { 
  plot(Global_active_power~Datetime, type="l", ylab="Global Active Power (kilowatts)", xlab="")
  plot(Voltage~Datetime,type="l", ylab = "Voltage (volt)", xlab="")
plot(Sub_metering_1 ~ Datetime, type= "l", ylab = "Energy Submetering", xlab="") 
lines(Sub_metering_2 ~ Datetime, col="red")
lines(Sub_metering_3 ~ Datetime, col= "blue")
plot(Global_reactive_power ~Datetime, type="l", ylab = "Global reactive power (Kilowatts", xlab="")
})
dev.copy(png, "Plot4.png", width=480, height=480)
dev.off()
